### ISSUE TITLE
KConnFlag_CopySendBuffer定义小小歧义

### ISSUE THREAD

**Issue by loveleon** [sryanyuan/tcpnetwork#1]
KConnFlag_CopySendBuffer //do not copy the send buffer 
在connect.go第300行处，
        	//	copy send buffer
	if 0 != f&KConnFlag_CopySendBuffer {
此处，如果f为1，等号右边为运算结果为1,那么0！=1 ，执行了copy buffer动作。枚举说明不相符。
KConnFlag_NoHeader 的说明和connec.go第401行用法，也有出入。

**Comment by sryanyuan** [comment]
注释的确有点问题
