### ISSUE TITLE
echo_example.go 测试用例出错

### ISSUE THREAD

**Issue by loveleon** [sryanyuan/tcpnetwork#2]
当把Send函数的flag置为2时候，会报错。

**Comment by sryanyuan** [comment]
Send函数的flag是一个比特位的标识，最低位的那个比特位表示是否拷贝数据，当设置为1的时候不会拷贝，下一位是是否写入数据头，假如不写入数据头，那么当前的协议是无法解包的，这个主要是用于自己设定协议，自己解包的情况。
